### ISSUE TITLE
Use the new Framework API?

### ISSUE THREAD

**Issue by jonniebigodes** [maraisr/storybook-addon-grid#16]
### Is this feature in relation to a problem?

 Hey @maraisr!
I'm one of the Storybook maintainers. I focus primarily on documentation and community outreach. I'm opening up this issue and letting you know that the Storybook API for building addons is currently being updated to factor in the changes introduced by the upcoming 7.0 release. If you're interested in making the required changes to help the community from benefiting from using your addon, we've prepared an abridged guide for the required changes [here](https://chromatic-ui.notion.site/Addon-migration-for-Storybook-7-002f2f627c1d470298ca94894ab8a040), and if you have any questions or issues, please reach out to us in the #prerelease channel in our [Discord Server](https://discord.gg/storybook). 

Hope you have a great day!

Stay safe

### Describe the solution you'd like

Per the description above we'd love to hear your thoughts on the document the Storybook maintainers provided either via Discord or directly in this issue so that the addon can start using the new API being implemented for Storybook 7.

### Alternative

N/A

### Additional context

N/A

**Comment by theKashey** [comment]
🤔 how to support Storybook 6 and 7 simultaneously? The required changes does not seems to be backward compatible. With some projects still using Storybook 5 (🤷‍♂️) things can get a little complicated.

Probably some bridge package, the one to be injected via package resolutions for example, could be a good answer to this problem.

**Comment by jonniebigodes** [comment]
I understand your reasoning, but path moving forward, it's probably more than time to remove support for Storybook version 5.x as it's vastly outdated with all the changes that 6.x introduced and now 7.x? What do you think? And to address the changes between Storybook versions 6 and 7, the new version (7.x) of the addon could be published as a canary version or something of that nature, so that gives users time to migrate and to catch potential issues from the Storybook side of things (e.g., API). Will that work for you?

Looking forward to hearing your thoughts on this.

Have a great day.

**Comment by JReinhold** [comment]
Hi @theKashey, Storybook v7.0.0 is out! It's only on the `next` tag for now, but it's still targetable with the `^7.0.0` semver range, so you should be able to develop against it with no dependency issues.

As @jonniebigodes says, my recommendation would be that you release a new major version of this addon that supports v7, and if you want to continue making changes that supports v6, you release a minor or a patch of the previous major version. Given that you're still in v0.x that makes things a little difficult, you'd basically have to promote your current v6 support to a v1 release, and release the v7 support as a v2. That way you can work on v1 and v2 simultaneously. It's a bit complicated though, so most people just support the latest upstream versions when doing new changes, but that's not for me to decide obviously.

If you hit any issues with v7, we've written a migration guide for addon authors [here](https://github.com/storybookjs/storybook/blob/norbert/add-addon-migration-guide/MIGRATION.md?rgh-link-date=2023-03-31T20%3A36%3A23Z#specific-instructions-for-addon-creators) and [here](https://chromatic-ui.notion.site/Addon-migration-for-Storybook-7-002f2f627c1d470298ca94894ab8a040).

You're also free to reach out to us in the #prerelease channel on our [Discord Server](https://discord.gg/storybook) and we'll happily help you out!

cc @ndelangen

**Comment by lukemcd-hero** [comment]
+1 for updating to Storybook 7. We leverage this add-on extensively for the workflow with our design team.

@maraisr hoping this update does not require a big lift.

**Comment by lukemcd-hero** [comment]
For anyone looking for Storybook 7 support it looks like this project was branched off of storybook-addon-grid but works with v7:
https://github.com/davidbepa/storybook-addon-grid-overlay

**Comment by yuriystasiv** [comment]
Hi @maraisr, is there any chance your addon will support Storybook 7 in the near future?

**Comment by maraisr** [comment]
@yuriystasiv ill take a look this week.

**Comment by maraisr** [comment]
This has been completed: please upgrade to using `storybook-addon-grid@0.4.0`. If you find any issues, feel free to comment those in this issue. But will close as complete for now.

Appreciate everyones patience here with this one.
