### ISSUE TITLE
Feature request: Responsive grid

### ISSUE THREAD

**Issue by tflx** [maraisr/storybook-addon-grid#5]
Sometimes the grid changes on different breakpoints. It would be great to have that option in the parameters too.
Great work BTW.

**Comment by maraisr** [comment]
This sounds like a fantastic idea, thansk @tflx! Any idea on how you'd expect this api to look?

Something like?
```js
export const parameters = {
  grid: {
    gridOn: true,
    columns: 5,
    ['@media (min-width: 1024px)']: {
       columns: 12
    }
  },
};
```

Each of the parameters already pipe directly into css, so `gap: 'var(--gap)'` is valid (and actually how I use it), which means its 100% controlled by your css—maybe we just need to have the same idea, but for the column count?

**Comment by theKashey** [comment]
technically speaking it should be somehow connected to storybook viewports - https://storybook.js.org/docs/react/essentials/viewport#add-new-devices - but viewports are more about _devices_ than breaking points, while the grid is about breaking points.

**Comment by tflx** [comment]
> This sounds like a fantastic idea, thansk @tflx! Any idea on how you'd expect this api to look?
> 
> Something like?
> 
> ```js
> export const parameters = {
>   grid: {
>     gridOn: true,
>     columns: 5,
>     ['@media (min-width: 1024px)']: {
>        columns: 12
>     }
>   },
> };
> ```
> 
> Each of the parameters already pipe directly into css, so `gap: 'var(--gap)'` is valid (and actually how I use it), which means its 100% controlled by your css—maybe we just need to have the same idea, but for the column count?

Yes, that was how I was imagining the syntax too.
Tying it to your existing css custom properties sounds even better - I love that. Of course that won't work when working with older browsers.

**Comment by theKashey** [comment]
The "grid" part will fail first :)

**Comment by maraisr** [comment]
> 
> 
> technically speaking it should be somehow connected to storybook viewports - https://storybook.js.org/docs/react/essentials/viewport#add-new-devices - but viewports are more about _devices_ than breaking points, while the grid is about breaking points.

I do like this idea of connecting it to viewports. Easier to configure and hooks right into the rest of the eco, what the api will look like not too sure. 

my Idea for the `@media` style thing, i'm starting to not like, feels too technical to me.

> Of course that won't work when working with older browsers.

Yeah as @theKashey  said, we use css-grids to display the columns guides, which will break well before css variables do. So think we're safe there.

---

Let me have a think, and ill tinker a few solutions and ill be sure to tag you in a PR! In the mean time, think you can send me your current breakpoints, or how you indent to tangibly use this feature?

@theKashey  does @thearnica have a use-case for this??

**Comment by maraisr** [comment]
Hi all, 

This puppy can be divided into 2 camps, both have pros and cons. 

1. Own config:
   ```
    grid: {
      columns: 12,
      viewports: {
         750: {
             columns: 8
          }
     }
    },
   ```
2. inherited config:
    ```
    grid: {
      columns: 12,
      viewports: {
         mobile: {
             columns: 8
          }
     }
    },
    ```

Both of those look identical as far as config would be considered—just one defines its own breakpoints, and the other inherits it.

Few considerations there;
- Viewports defined as dimensions. Which isnt too bad, we can just get the width
- Chromatic doesnt care about viewports, so the `/chromatic` package would need to source the dimensions from somewhere when its rendering the story in its format.

The point on Chromatic isnt that bad, chances are people will just be defining the grids at a config level, and not override it at story level as much, which means the breakpoints would co-exist in relevantly the same place as the config for this addon.

Chromatic is also width based as an array, so the named viewport connection might break there.

So our choice is really, made for us. I like the idea of named viewports, a lot easier to say "i want 4 columns on my logical mobile viewport" than "i want 4 columns on my 750 breakpoint". But to get that to play nicely with chromatic, we _could_ will just mean the consumer of the addon will need to define a `{mobile: 750}` object, and `Object.values` that into Chromatics config, and then simply give that object to viewports, then just `mobile: { columns: 4 }` in the addon.

Thoughts??

---

example of how I think all of this _can_ work together.

```ts
const viewports = {
	mobile1: {
		name: "Small mobile",
		styles: {
			height: "568px",
			width: "320px",
		},
		type: "mobile",
	},
};

export const parameters = {
	viewport: {
		viewports,
	},
	chromatic: {
		viewports: Object.values(viewports)
			.map(i => i.styles.width.replace("px", ""))
	},
	grid: {
		columns: 12,
		viewports: {
			mobile1: { columns: 4 },
		},
	},
};

```

**Comment by theKashey** [comment]
So the only problem here is to double-check that all used viewports do exist.
Or it's not a problem at all?

**Comment by maraisr** [comment]
I think this is up to the consumer—if they dont want Chromatic to render all viewports, then let them not configure all. Similarly if you want more viewports (addon) than Chromatic or viewports addon, then its your choice. 

Its more that—andy maybe our answer—do we want to couple this addon with viewports? Maybe we just do a chromatic and `{750: {columns: 4}}`

**Comment by theKashey** [comment]
- if you do `{750: {columns: 4}}` you will let end customer generate viewports in any way they like (you cannot make a mistake doing this)
- if you do `{mobile1: {columns: 4}}` you bound grid to storybook viewports, which they don't have to use actually (you can make a mistake doing this)

**Comment by maraisr** [comment]
Will leave some time for others to chime in—but think consensus is to go with `{750: {columns: 4}}` approach.

**Comment by tlkiong** [comment]
I would like to add one thing.
Generally when the designer set the grids, they don't set it based on the device but a group of devices. It'll be grouped by the viewport size.

Hence, I'm leaning towards `{750: {columns: 4}`. However, I have a question on this. 
Does `{750: {columns: 4}` means which: 
1. `0 <= size <= 750`, number of columns = 4
2. `0 <= size < 750`, number of columns = 4

**Comment by tlkiong** [comment]
@maraisr 

If that means that it supports all supported CSS media queries, then it'll be perfect.

**Comment by Julianwan** [comment]
I'm really excited to see this go responsive... any updates? :D

**Comment by maraisr** [comment]
Hi all,

Yeah so there is a WIP branch — will push up maybe ya'll can help me. Just been MIA on this one, got blocked on dynamically generating columns (divs) for every breakpoint. 

So side stepped, but need to get back into this. 

cc @tlkiong @Julianwan 

any thoughts @thearnica and @theKashey

**Comment by theKashey** [comment]
Sorry @maraisr, I am going to add more confusion than solution 😅

What about
```diff
const viewports = {
	mobile1: {
		name: "Small mobile",
		styles: {
			height: "568px",
			width: "320px",
		},
		type: "mobile",
+               columns: 4
	},
};
```
That will "align" viewpoints to the grid

or what about
```diff
export const parameters = {
	viewport: {
		viewports,
	},
	chromatic: {
		viewports: Object.values(viewports)
			.map(i => i.styles.width.replace("px", ""))
	},
	grid: {
		columns: 12,
// actually should be observable/async genetator
+		getOptions: () => window.width/MAGIC_NUMBER || matchMedia
	},
};
```
that will  allow user to have any logic they might want

**Comment by tlkiong** [comment]
@maraisr Maybe you can push up a WIP branch and share here where we can all help to contribute on it to move it along?

**Comment by maraisr** [comment]
Sure! You can see here — https://github.com/maraisr/storybook-addon-grid/commit/da058d8fccae09c94c71c7760fae26e6e17809c5

But as @theKashey said, maybe that way would be the better one.

**Comment by israelKusayev** [comment]
Hi is it still WIP?

**Comment by theKashey** [comment]
Was looking into this issue once again and was wondering if I want any configuration from this plugin being provided from the "top", or I want behavior provided from the bottom.

Currently it uses [useParameters](https://storybook.js.org/docs/react/addons/addons-api#useparameter) to be given configuration, but I don't see any "story facing" `useSetParameters` to let client-code provide configuration as the client wants.

Not sure _how_ I want to see this working, but I know _what_ I want - shift the responsibility of providing and updating configuration from this addon to any other place.

**Comment by theKashey** [comment]
🕺 the answer was always just behind the corner. Not everything should be replicated, sometimes one should just follow the flow.
Wondering if one day the course of this implementation can encourage others to "use the platform" more often, even if that platform is the host application.
