### ISSUE TITLE
Allow left-aligned columns (with padding)

### ISSUE THREAD

**Issue by fabiradi** [maraisr/storybook-addon-grid#6]
This might be an _odd_ requirement, but I need the grid to be aligned left, **not centered**. I really do not want to create my own addon (or fork/duplicate this one).

Technically, it is just an issue with the current `margin`.
https://github.com/maraisr/storybook-addon-grid/blob/06b10bd908b597567980fbe2b09730ccd42831fe/src/components/Grids.tsx#L59

It needs to be something like this, if an **alignment parameter** is set to `left` instead of `centered` (default). Or just use `centered: true` vs. `centered: false` (not sure)?

```javascript
    margin: centered ? '0 auto' : '0', // "gutterLeft" will still define padding to the left
```

> I'm not quite sure about the naming/variables. It's just an example.

🤷🏻  I _could_ create a pull request? Or would you rather implement it yourself?

**Comment by theKashey** [comment]
I would not call this requirement really "odd" - in many circumstances having your components at the beginning of coordinates is useful.

However it's worth to doublecheck - is it actually desired behavior or just an "enforced" requirement? Just trying to walk in your shoes.

**Comment by maraisr** [comment]
Hi @fabiradi  thank you so much for trusting in my library within your project and seeking ways to use it more! 🙏🏻 

As per @theKashey I'm also trying to understand those things, so would be interested to hear more (can also help influence the direction, maybe I missed something).

Also, yeah by all means feel free to open a PR — let me know if the flow doesn't quite work, but ya would be more than happy to take a look if you raise it. If you don't have the time, and after our chat can also help get this feature in.

Still on struggle street for responsive values re #5, so do appreciate the help <3

**Comment by fabiradi** [comment]
> However it's worth to doublecheck - is it actually desired behavior or just an "enforced" requirement? Just trying to walk in your shoes.

Well, the stories are left-aligned. The also have additional documentation below it. That's probably the reason why the content is left-aligned. I would have liked to use the docs feature more, but people did not find it without additional info. Most stories also have some kind of controls below it to manipulate the content.

> I would have to find out, if we could center all stories. But the question is: Why would we have to change the layout of our stories to fit a 3rd party addon? I know that I will have to answer that question at some point. I'm not sure if I can explain that ...

**Comment by maraisr** [comment]
I feel generally this addon is more useful for page level stories, which are generically representative of full width stories. That being said, lower level components this also benefits. 

Ill take a look in the morning what this means, and release a feature of some kind to enable this.

**Comment by theKashey** [comment]
You've said it - `page level` and `component level` - it's not about left or center alignment, it's about the "container".
For example in the component use case, with some controls underneath (why not in the action panel?) one might want to limit the height of the grid as well.

**Comment by maraisr** [comment]
@fabiradi sorry for the hiatus — are you able to help me with a more tangible use-case? The only one I can think off is that stories like component level ones, exist on the left of the preview viewport (with no preview gutter), and thus the grid does in fact make sense, BUT only if the component is also the width of the grids.

Which is all fair and well, and is your implementation detail. I think it's fair to add this behaviour, with a little more context. API adoption for something I personally won't use, just leads me as a maintainer down a path of maintaining something I have no idea about.

I will close for now, but am open to reopening in anycase
