### ISSUE TITLE
grid not appearing in Storybook 6.5

### ISSUE THREAD

**Issue by lukemcd-hero** [maraisr/storybook-addon-grid#8]
Since upgrading to Storybook 6.5 the grid add-on is no longer displaying for me. Our project currently uses React 17, Storybook 6.5.8 and storybook-addon-grid 0.1.0. Curious if anyone else is facing this issue.

**Comment by maraisr** [comment]
Hi @lukemcd-hero sorry about this — and thanks so much for the issue 🙏🏻 

In the past versions of storybook they didn't expose the Emotion cache provider's used (at least from what I can remember) to render the grid in the preview (without using the decorator pattern) — they now do include this, and is "home-cooked" with exposing everything we need. But if we used emotion directly, it'll cause havoc with the required singletons.

Either way all good, resolved! 🚀 

Please try v0.2.0

**Comment by lukemcd-hero** [comment]
Thanks for the quick response @maraisr ! Upgraded to 0.2.0 on my project and now the grid add-on is displaying perfectly. Appreciate the work!
